name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub runner environment (Ubuntu)

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Install Checkstyle and run linting
      - name: Install Checkstyle
        run: wget -qO checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.2/checkstyle-10.12.2-all.jar

      - name: Run Checkstyle Linting
        run: java -jar checkstyle.jar -c /google_checks.xml src/ || true

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: docker build -t hello-world-java:latest .

      # Step 5: Save Docker image to a local folder
      - name: Save Docker image to local folder
        run: docker save hello-world-java:latest > Output_Image/hello-world-java.tar
